# -*- coding: utf-8 -*-
"""ann

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWCIkWCE2XeKSUZOL2XHIksjf7SyLHMW
"""

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Clear session & set seed
tf.keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

# Load Dataset
data = pd.read_csv('Maternal Health Risk Data Set.csv')

# Display the first 5 rows of the dataset
print("First 5 rows of the dataset:")
display(data.head())

print("TensorFlow version :", tf.__version__)

# Display basic information about the DataFrame
print("\nDataFrame Info:")
data.info()

# Display descriptive statistics
print("\nDescriptive Statistics:")
display(data.describe())

# Check for missing values
print("\nMissing values per column:")
display(data.isnull().sum())

"""### Data Preprocessing

First, we'll encode the target variable `RiskLevel` from categorical to numerical representation. Then, we'll separate the features (X) from the target (y), split the data into training and testing sets, and finally, scale the numerical features using `StandardScaler`.
"""

# Encode the target variable 'RiskLevel'
label_encoder = LabelEncoder()
data['RiskLevel_encoded'] = label_encoder.fit_transform(data['RiskLevel'])

# Display the mapping of original to encoded labels
print("RiskLevel mapping:")
for i, label in enumerate(label_encoder.classes_):
    print(f"{label}: {i}")

# Define features (X) and target (y)
X = data.drop(['RiskLevel', 'RiskLevel_encoded'], axis=1)
y = data['RiskLevel_encoded']

# Split the data into training and testing sets
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42, stratify=y
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.15, random_state=42, stratify=y_train_val
)

print("Train size      :", X_train.shape)
print("Validation size :", X_val.shape)
print("Test size       :", X_test.shape)

# Scale numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

print("Features scaled successfully.")

# Define the ANN model
model = keras.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)), # Input layer
    layers.Dense(128, activation='relu',kernel_initializer=tf.keras.initializers.HeNormal, name='hidden_layer_1'), # First hidden layer
    layers.Dropout(0.2), # Dropout for regularization
    layers.Dense(64, activation='relu',kernel_initializer=tf.keras.initializers.HeNormal, name='hidden_layer_2'), # Second hidden layer
    layers.Dropout(0.2), # Dropout for regularization
    layers.Dense(len(label_encoder.classes_), activation='softmax',kernel_initializer=tf.keras.initializers.GlorotNormal, name='output_layer') # Output layer
])


# Display model summary
print("ANN Model Summary:")
model.summary()

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print("Model compiled.")

"""### Train the ANN Model

Next, we'll train the ANN model using the scaled training data. We'll specify the number of epochs and batch size, and include a validation split to monitor performance during training.
"""

# early_stopping = tf.keras.callbacks.EarlyStopping(
#     monitor='val_loss',
#     patience=5,
#     restore_best_weights=True
# )

model_checkpoint = tf.keras.callbacks.ModelCheckpoint(
    filepath='best_model.keras',
    monitor='val_loss',
    save_best_only=True
)

callbacks = [model_checkpoint]

print("Callbacks berhasil.")

# Train the model
history = model.fit(
    X_train_scaled, y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_val_scaled, y_val),
    callbacks=callbacks,
    verbose=1)

print("Model training complete.")

# --- Plot Learning Curve ---
def plot_history(history, title="Training History"):
    history_df = pd.DataFrame(history.history)

    plt.figure(figsize=(21, 5))

    plt.subplot(1, 2, 1)
    sns.lineplot(data=history_df[['accuracy', 'val_accuracy']])
    plt.title(f"{title} — Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.grid(True)

    plt.subplot(1, 2, 2)
    sns.lineplot(data=history_df[['loss', 'val_loss']])
    plt.title(f"{title} — Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)

    plt.tight_layout()
    plt.show()

plot_history(history, title="Training Vs Validation")

# Make predictions on the test set
def evaluate_model(model, X_test_scaled, y_test, label="Model"):
    loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
    # For multi-class classification with softmax output, y_pred should be the index of the class with the highest probability
    y_pred_probs = model.predict(X_test_scaled, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)

    print(f"{'='*45}")
    print(f"  {label} — Test Set Results")
    print(f"{'='*45}")
    print(f"  Loss     : {loss:.4f}")
    print(f"  Accuracy : {accuracy:.4f} ({accuracy*100:.1f}%)")
    print()
    # Use label_encoder.classes_ for target_names
    print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_,
                yticklabels=label_encoder.classes_)
    plt.title(f"{label} — Confusion Matrix")
    plt.ylabel("Actual")
    plt.xlabel("Predicted")
    plt.tight_layout()
    plt.show()

evaluate_model(model, X_test_scaled, y_test, label="Model")

# Save the entire model
model_save_path = 'ann_model.keras'
model.save(model_save_path)

print(f"Model saved successfully to {model_save_path}")

import joblib

joblib.dump(
    scaler,
    "scaler.joblib"
)

# import joblib

# joblib_save_path = 'ann_model.joblib'
# joblib.dump(model, joblib_save_path)

# print(f"Model saved successfully to {joblib_save_path} using joblib.")